version: '3.8'

services:
  sora-bot:
    build: .
    container_name: sora-bot
    restart: always
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    environment:
      - TZ=Europe/Moscow
    ports:
      - "5478:8080"
    depends_on:
      - redis
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    
  callback:
    container_name: sora-callback
    build:
      context: .
      dockerfile: Fastapi.Dockerfile
    restart: always
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    ports:
      - "3849:8000"
    
  redis:
    container_name: sora-redis
    image: redis:7-alpine
    restart: always
    volumes:
      - redis-data:/data

volumes:
  postgres_data:
  redis-data: